#!/usr/bin/env bash
# VulnSync — Install git hooks
set -euo pipefail

HOOK_DIR=".git/hooks"
PRE_COMMIT="$HOOK_DIR/pre-commit"

mkdir -p "$HOOK_DIR"

cat > "$PRE_COMMIT" << 'HOOK'
#!/usr/bin/env bash
# VulnSync pre-commit hook — auto-generated by install-hooks.sh
set -euo pipefail

if command -v vulnsync &>/dev/null; then
    exec vulnsync hook pre-commit
fi
HOOK

chmod +x "$PRE_COMMIT"
echo "✅ VulnSync pre-commit hook installed → $PRE_COMMIT"
echo "   To uninstall: rm $PRE_COMMIT"
